language: erlang
notifications:
  recipients:
    - esente@gmail.com
    - sdfippinger@gmail.com
otp_release:
  - R16B
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/v0.11.0/v0.11.0.zip && unzip -qq v0.11.0.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
script:
  - mix test
install: mix deps.get
